// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module scaled_fixed2ieee (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V,
        prescale,
        ap_return
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [62:0] in_V;
input  [11:0] prescale;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] i_5_fu_247_p2;
reg   [1:0] i_5_reg_613;
wire    ap_CS_fsm_state2;
reg   [1:0] out_bits_V_addr_1_reg_618;
wire   [0:0] exitcond6_fu_241_p2;
wire   [2:0] i_6_fu_409_p2;
reg   [2:0] i_6_reg_626;
wire    ap_CS_fsm_state4;
wire   [63:0] tmp_62_fu_415_p1;
reg   [63:0] tmp_62_reg_631;
wire   [0:0] exitcond_fu_403_p2;
wire   [0:0] tmp_99_fu_439_p3;
reg   [0:0] tmp_99_reg_641;
wire    ap_CS_fsm_state6;
wire   [2:0] i_7_fu_447_p2;
reg   [2:0] i_7_reg_645;
wire   [31:0] shift_2_fu_458_p2;
wire    ap_CS_fsm_state7;
wire   [62:0] r_V_36_fu_503_p3;
reg   [1:0] out_bits_V_address0;
reg    out_bits_V_ce0;
reg   [3:0] out_bits_V_we0;
reg   [31:0] out_bits_V_d0;
wire   [31:0] out_bits_V_q0;
reg   [1:0] c_address0;
reg    c_ce0;
reg    c_we0;
reg   [31:0] c_d0;
wire   [31:0] c_q0;
reg   [1:0] i_reg_165;
wire    ap_CS_fsm_state3;
reg   [2:0] i1_reg_177;
wire    ap_CS_fsm_state5;
reg   [62:0] p_s_reg_188;
wire   [0:0] tmp_67_fu_512_p2;
reg   [31:0] shift_reg_198;
reg   [2:0] i2_reg_210;
reg   [62:0] ap_phi_mux_p_Val2_9_in_phi_fu_224_p4;
reg   [62:0] p_Val2_9_in_reg_221;
reg   [31:0] ap_phi_mux_shift_1_phi_fu_234_p4;
reg   [31:0] shift_1_reg_231;
wire   [63:0] tmp_fu_253_p1;
wire   [63:0] tmp_64_fu_453_p1;
wire   [31:0] tmp_83_fu_261_p3;
wire   [31:0] p_Result_4_fu_390_p5;
wire   [14:0] tmp_82_fu_258_p1;
wire   [5:0] tmp_s_fu_270_p3;
wire   [5:0] Lo_assign_fu_284_p2;
wire   [5:0] Hi_assign_fu_278_p2;
wire   [0:0] tmp_84_fu_290_p2;
wire   [5:0] tmp_86_fu_305_p2;
wire   [5:0] tmp_88_fu_317_p2;
reg   [62:0] tmp_85_fu_296_p4;
wire   [5:0] tmp_87_fu_311_p2;
wire   [5:0] tmp_89_fu_323_p3;
wire   [5:0] tmp_91_fu_338_p3;
wire   [5:0] tmp_92_fu_346_p2;
wire   [62:0] tmp_90_fu_331_p3;
wire   [62:0] tmp_93_fu_352_p1;
wire   [62:0] tmp_94_fu_356_p1;
wire   [62:0] tmp_95_fu_360_p2;
wire   [62:0] tmp_96_fu_366_p2;
wire   [62:0] p_Result_s_fu_372_p2;
wire   [15:0] tmp_98_fu_378_p1;
wire   [16:0] tmp_61_fu_382_p3;
reg   [31:0] p_Result_39_fu_420_p4;
wire   [0:0] isNeg_fu_465_p3;
wire   [31:0] tmp_65_fu_473_p2;
wire   [31:0] ush_fu_479_p3;
wire   [62:0] tmp_66_fu_487_p1;
wire   [62:0] r_V_fu_491_p2;
wire   [62:0] r_V_8_fu_497_p2;
wire   [11:0] tmp_68_fu_518_p2;
wire  signed [31:0] tmp_82_cast_fu_523_p1;
wire   [31:0] newexp_fu_527_p2;
wire   [0:0] tmp_101_fu_533_p3;
wire   [0:0] tmp_69_fu_541_p2;
wire   [0:0] or_cond_fu_546_p2;
wire   [51:0] phitmp1_fu_556_p4;
wire   [10:0] tmp_102_fu_552_p1;
wire   [10:0] out_exp_V_fu_574_p3;
wire   [51:0] significand_V_fu_566_p3;
wire   [63:0] p_Result_40_fu_582_p4;
wire   [63:0] result_write_assign_fu_592_p1;
reg   [63:0] ap_return_preg;
reg   [6:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_return_preg = 64'd0;
end

scaled_fixed2ieee_out_bits_V #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
out_bits_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_bits_V_address0),
    .ce0(out_bits_V_ce0),
    .we0(out_bits_V_we0),
    .d0(out_bits_V_d0),
    .q0(out_bits_V_q0)
);

scaled_fixed2ieee_c #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(c_address0),
    .ce0(c_ce0),
    .we0(c_we0),
    .d0(c_d0),
    .q0(c_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_preg[0] <= 1'b0;
        ap_return_preg[1] <= 1'b0;
        ap_return_preg[2] <= 1'b0;
        ap_return_preg[3] <= 1'b0;
        ap_return_preg[4] <= 1'b0;
        ap_return_preg[5] <= 1'b0;
        ap_return_preg[6] <= 1'b0;
        ap_return_preg[7] <= 1'b0;
        ap_return_preg[8] <= 1'b0;
        ap_return_preg[9] <= 1'b0;
        ap_return_preg[10] <= 1'b0;
        ap_return_preg[11] <= 1'b0;
        ap_return_preg[12] <= 1'b0;
        ap_return_preg[13] <= 1'b0;
        ap_return_preg[14] <= 1'b0;
        ap_return_preg[15] <= 1'b0;
        ap_return_preg[16] <= 1'b0;
        ap_return_preg[17] <= 1'b0;
        ap_return_preg[18] <= 1'b0;
        ap_return_preg[19] <= 1'b0;
        ap_return_preg[20] <= 1'b0;
        ap_return_preg[21] <= 1'b0;
        ap_return_preg[22] <= 1'b0;
        ap_return_preg[23] <= 1'b0;
        ap_return_preg[24] <= 1'b0;
        ap_return_preg[25] <= 1'b0;
        ap_return_preg[26] <= 1'b0;
        ap_return_preg[27] <= 1'b0;
        ap_return_preg[28] <= 1'b0;
        ap_return_preg[29] <= 1'b0;
        ap_return_preg[30] <= 1'b0;
        ap_return_preg[31] <= 1'b0;
        ap_return_preg[32] <= 1'b0;
        ap_return_preg[33] <= 1'b0;
        ap_return_preg[34] <= 1'b0;
        ap_return_preg[35] <= 1'b0;
        ap_return_preg[36] <= 1'b0;
        ap_return_preg[37] <= 1'b0;
        ap_return_preg[38] <= 1'b0;
        ap_return_preg[39] <= 1'b0;
        ap_return_preg[40] <= 1'b0;
        ap_return_preg[41] <= 1'b0;
        ap_return_preg[42] <= 1'b0;
        ap_return_preg[43] <= 1'b0;
        ap_return_preg[44] <= 1'b0;
        ap_return_preg[45] <= 1'b0;
        ap_return_preg[46] <= 1'b0;
        ap_return_preg[47] <= 1'b0;
        ap_return_preg[48] <= 1'b0;
        ap_return_preg[49] <= 1'b0;
        ap_return_preg[50] <= 1'b0;
        ap_return_preg[51] <= 1'b0;
        ap_return_preg[52] <= 1'b0;
        ap_return_preg[53] <= 1'b0;
        ap_return_preg[54] <= 1'b0;
        ap_return_preg[55] <= 1'b0;
        ap_return_preg[56] <= 1'b0;
        ap_return_preg[57] <= 1'b0;
        ap_return_preg[58] <= 1'b0;
        ap_return_preg[59] <= 1'b0;
        ap_return_preg[60] <= 1'b0;
        ap_return_preg[61] <= 1'b0;
        ap_return_preg[62] <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & ((tmp_99_reg_641 == 1'd1) | (tmp_67_fu_512_p2 == 1'd0)))) begin
                        ap_return_preg[62 : 0] <= result_write_assign_fu_592_p1[62 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i1_reg_177 <= i_6_reg_626;
    end else if (((exitcond6_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_reg_177 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_403_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i2_reg_210 <= 3'd0;
    end else if (((tmp_99_reg_641 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (tmp_67_fu_512_p2 == 1'd1))) begin
        i2_reg_210 <= i_7_reg_645;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_165 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_165 <= i_5_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_99_reg_641 == 1'd0) & (tmp_67_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        p_Val2_9_in_reg_221 <= r_V_36_fu_503_p3;
    end else if (((tmp_99_fu_439_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        p_Val2_9_in_reg_221 <= p_s_reg_188;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_403_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_s_reg_188 <= in_V;
    end else if (((tmp_99_reg_641 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (tmp_67_fu_512_p2 == 1'd1))) begin
        p_s_reg_188 <= r_V_36_fu_503_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_99_reg_641 == 1'd0) & (tmp_67_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        shift_1_reg_231 <= shift_2_fu_458_p2;
    end else if (((tmp_99_fu_439_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        shift_1_reg_231 <= shift_reg_198;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_403_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        shift_reg_198 <= 32'd0;
    end else if (((tmp_99_reg_641 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (tmp_67_fu_512_p2 == 1'd1))) begin
        shift_reg_198 <= shift_2_fu_458_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_5_reg_613 <= i_5_fu_247_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_6_reg_626 <= i_6_fu_409_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_7_reg_645 <= i_7_fu_447_p2;
        tmp_99_reg_641 <= i2_reg_210[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond6_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_V_addr_1_reg_618 <= tmp_fu_253_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_403_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_62_reg_631[2 : 0] <= tmp_62_fu_415_p1[2 : 0];
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state7) & ((tmp_99_reg_641 == 1'd1) | (tmp_67_fu_512_p2 == 1'd0))) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_99_reg_641 == 1'd0) & (tmp_67_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_phi_mux_p_Val2_9_in_phi_fu_224_p4 = r_V_36_fu_503_p3;
    end else begin
        ap_phi_mux_p_Val2_9_in_phi_fu_224_p4 = p_Val2_9_in_reg_221;
    end
end

always @ (*) begin
    if (((tmp_99_reg_641 == 1'd0) & (tmp_67_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_phi_mux_shift_1_phi_fu_234_p4 = shift_2_fu_458_p2;
    end else begin
        ap_phi_mux_shift_1_phi_fu_234_p4 = shift_1_reg_231;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & ((tmp_99_reg_641 == 1'd1) | (tmp_67_fu_512_p2 == 1'd0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & ((tmp_99_reg_641 == 1'd1) | (tmp_67_fu_512_p2 == 1'd0)))) begin
        ap_return = result_write_assign_fu_592_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        c_address0 = tmp_64_fu_453_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        c_address0 = tmp_62_reg_631;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        c_we0 = 1'b1;
    end else begin
        c_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_bits_V_address0 = tmp_62_fu_415_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_bits_V_address0 = out_bits_V_addr_1_reg_618;
    end else if (((exitcond6_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_V_address0 = 64'd3;
    end else if (((exitcond6_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_V_address0 = tmp_fu_253_p1;
    end else begin
        out_bits_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond6_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((exitcond6_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        out_bits_V_ce0 = 1'b1;
    end else begin
        out_bits_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_bits_V_d0 = p_Result_4_fu_390_p5;
    end else if (((exitcond6_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_V_d0 = tmp_83_fu_261_p3;
    end else begin
        out_bits_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_bits_V_we0 = 4'd15;
    end else if (((exitcond6_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_V_we0 = 4'd12;
    end else begin
        out_bits_V_we0 = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond6_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond_fu_403_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((tmp_99_reg_641 == 1'd1) | (tmp_67_fu_512_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Hi_assign_fu_278_p2 = ($signed(6'd62) - $signed(tmp_s_fu_270_p3));

assign Lo_assign_fu_284_p2 = ($signed(6'd47) - $signed(tmp_s_fu_270_p3));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];


always @ (p_Result_39_fu_420_p4) begin
    if (p_Result_39_fu_420_p4[0] == 1'b1) begin
        c_d0 = 32'd0;
    end else if (p_Result_39_fu_420_p4[1] == 1'b1) begin
        c_d0 = 32'd1;
    end else if (p_Result_39_fu_420_p4[2] == 1'b1) begin
        c_d0 = 32'd2;
    end else if (p_Result_39_fu_420_p4[3] == 1'b1) begin
        c_d0 = 32'd3;
    end else if (p_Result_39_fu_420_p4[4] == 1'b1) begin
        c_d0 = 32'd4;
    end else if (p_Result_39_fu_420_p4[5] == 1'b1) begin
        c_d0 = 32'd5;
    end else if (p_Result_39_fu_420_p4[6] == 1'b1) begin
        c_d0 = 32'd6;
    end else if (p_Result_39_fu_420_p4[7] == 1'b1) begin
        c_d0 = 32'd7;
    end else if (p_Result_39_fu_420_p4[8] == 1'b1) begin
        c_d0 = 32'd8;
    end else if (p_Result_39_fu_420_p4[9] == 1'b1) begin
        c_d0 = 32'd9;
    end else if (p_Result_39_fu_420_p4[10] == 1'b1) begin
        c_d0 = 32'd10;
    end else if (p_Result_39_fu_420_p4[11] == 1'b1) begin
        c_d0 = 32'd11;
    end else if (p_Result_39_fu_420_p4[12] == 1'b1) begin
        c_d0 = 32'd12;
    end else if (p_Result_39_fu_420_p4[13] == 1'b1) begin
        c_d0 = 32'd13;
    end else if (p_Result_39_fu_420_p4[14] == 1'b1) begin
        c_d0 = 32'd14;
    end else if (p_Result_39_fu_420_p4[15] == 1'b1) begin
        c_d0 = 32'd15;
    end else if (p_Result_39_fu_420_p4[16] == 1'b1) begin
        c_d0 = 32'd16;
    end else if (p_Result_39_fu_420_p4[17] == 1'b1) begin
        c_d0 = 32'd17;
    end else if (p_Result_39_fu_420_p4[18] == 1'b1) begin
        c_d0 = 32'd18;
    end else if (p_Result_39_fu_420_p4[19] == 1'b1) begin
        c_d0 = 32'd19;
    end else if (p_Result_39_fu_420_p4[20] == 1'b1) begin
        c_d0 = 32'd20;
    end else if (p_Result_39_fu_420_p4[21] == 1'b1) begin
        c_d0 = 32'd21;
    end else if (p_Result_39_fu_420_p4[22] == 1'b1) begin
        c_d0 = 32'd22;
    end else if (p_Result_39_fu_420_p4[23] == 1'b1) begin
        c_d0 = 32'd23;
    end else if (p_Result_39_fu_420_p4[24] == 1'b1) begin
        c_d0 = 32'd24;
    end else if (p_Result_39_fu_420_p4[25] == 1'b1) begin
        c_d0 = 32'd25;
    end else if (p_Result_39_fu_420_p4[26] == 1'b1) begin
        c_d0 = 32'd26;
    end else if (p_Result_39_fu_420_p4[27] == 1'b1) begin
        c_d0 = 32'd27;
    end else if (p_Result_39_fu_420_p4[28] == 1'b1) begin
        c_d0 = 32'd28;
    end else if (p_Result_39_fu_420_p4[29] == 1'b1) begin
        c_d0 = 32'd29;
    end else if (p_Result_39_fu_420_p4[30] == 1'b1) begin
        c_d0 = 32'd30;
    end else if (p_Result_39_fu_420_p4[31] == 1'b1) begin
        c_d0 = 32'd31;
    end else begin
        c_d0 = 32'd32;
    end
end

assign exitcond6_fu_241_p2 = ((i_reg_165 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond_fu_403_p2 = ((i1_reg_177 == 3'd4) ? 1'b1 : 1'b0);

assign i_5_fu_247_p2 = (i_reg_165 + 2'd1);

assign i_6_fu_409_p2 = (i1_reg_177 + 3'd1);

assign i_7_fu_447_p2 = (i2_reg_210 + 3'd1);

assign isNeg_fu_465_p3 = c_q0[32'd31];

assign newexp_fu_527_p2 = ($signed(tmp_82_cast_fu_523_p1) - $signed(ap_phi_mux_shift_1_phi_fu_234_p4));

assign or_cond_fu_546_p2 = (tmp_69_fu_541_p2 | tmp_101_fu_533_p3);

assign out_exp_V_fu_574_p3 = ((or_cond_fu_546_p2[0:0] === 1'b1) ? 11'd0 : tmp_102_fu_552_p1);

integer ap_tvar_int_0;

always @ (out_bits_V_q0) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_39_fu_420_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_39_fu_420_p4[ap_tvar_int_0] = out_bits_V_q0[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_40_fu_582_p4 = {{{{1'd0}, {out_exp_V_fu_574_p3}}}, {significand_V_fu_566_p3}};

assign p_Result_4_fu_390_p5 = {{tmp_61_fu_382_p3}, {out_bits_V_q0[14:0]}};

assign p_Result_s_fu_372_p2 = (tmp_96_fu_366_p2 & tmp_95_fu_360_p2);

assign phitmp1_fu_556_p4 = {{ap_phi_mux_p_Val2_9_in_phi_fu_224_p4[61:10]}};

assign r_V_36_fu_503_p3 = ((isNeg_fu_465_p3[0:0] === 1'b1) ? r_V_fu_491_p2 : r_V_8_fu_497_p2);

assign r_V_8_fu_497_p2 = p_s_reg_188 << tmp_66_fu_487_p1;

assign r_V_fu_491_p2 = $signed(p_s_reg_188) >>> tmp_66_fu_487_p1;

assign result_write_assign_fu_592_p1 = p_Result_40_fu_582_p4;

assign shift_2_fu_458_p2 = (c_q0 + shift_reg_198);

assign significand_V_fu_566_p3 = ((or_cond_fu_546_p2[0:0] === 1'b1) ? 52'd0 : phitmp1_fu_556_p4);

assign tmp_101_fu_533_p3 = newexp_fu_527_p2[32'd31];

assign tmp_102_fu_552_p1 = newexp_fu_527_p2[10:0];

assign tmp_61_fu_382_p3 = {{tmp_98_fu_378_p1}, {1'd1}};

assign tmp_62_fu_415_p1 = i1_reg_177;

assign tmp_64_fu_453_p1 = i2_reg_210;

assign tmp_65_fu_473_p2 = (32'd0 - c_q0);

assign tmp_66_fu_487_p1 = ush_fu_479_p3;

assign tmp_67_fu_512_p2 = ((c_q0 == 32'd16) ? 1'b1 : 1'b0);

assign tmp_68_fu_518_p2 = (12'd1023 - prescale);

assign tmp_69_fu_541_p2 = ((in_V == 63'd0) ? 1'b1 : 1'b0);

assign tmp_82_cast_fu_523_p1 = $signed(tmp_68_fu_518_p2);

assign tmp_82_fu_258_p1 = in_V[14:0];

assign tmp_83_fu_261_p3 = {{tmp_82_fu_258_p1}, {17'd65536}};

assign tmp_84_fu_290_p2 = ((Lo_assign_fu_284_p2 > Hi_assign_fu_278_p2) ? 1'b1 : 1'b0);

integer ap_tvar_int_1;

always @ (in_V) begin
    for (ap_tvar_int_1 = 63 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 62 - 0) begin
            tmp_85_fu_296_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_85_fu_296_p4[ap_tvar_int_1] = in_V[62 - ap_tvar_int_1];
        end
    end
end

assign tmp_86_fu_305_p2 = (Lo_assign_fu_284_p2 - Hi_assign_fu_278_p2);

assign tmp_87_fu_311_p2 = ($signed(6'd62) - $signed(Lo_assign_fu_284_p2));

assign tmp_88_fu_317_p2 = (Hi_assign_fu_278_p2 - Lo_assign_fu_284_p2);

assign tmp_89_fu_323_p3 = ((tmp_84_fu_290_p2[0:0] === 1'b1) ? tmp_86_fu_305_p2 : tmp_88_fu_317_p2);

assign tmp_90_fu_331_p3 = ((tmp_84_fu_290_p2[0:0] === 1'b1) ? tmp_85_fu_296_p4 : in_V);

assign tmp_91_fu_338_p3 = ((tmp_84_fu_290_p2[0:0] === 1'b1) ? tmp_87_fu_311_p2 : Lo_assign_fu_284_p2);

assign tmp_92_fu_346_p2 = ($signed(6'd62) - $signed(tmp_89_fu_323_p3));

assign tmp_93_fu_352_p1 = tmp_91_fu_338_p3;

assign tmp_94_fu_356_p1 = tmp_92_fu_346_p2;

assign tmp_95_fu_360_p2 = tmp_90_fu_331_p3 >> tmp_93_fu_352_p1;

assign tmp_96_fu_366_p2 = 63'd9223372036854775807 >> tmp_94_fu_356_p1;

assign tmp_98_fu_378_p1 = p_Result_s_fu_372_p2[15:0];

assign tmp_99_fu_439_p3 = i2_reg_210[32'd2];

assign tmp_fu_253_p1 = i_reg_165;

assign tmp_s_fu_270_p3 = {{i_reg_165}, {4'd0}};

assign ush_fu_479_p3 = ((isNeg_fu_465_p3[0:0] === 1'b1) ? tmp_65_fu_473_p2 : c_q0);

always @ (posedge ap_clk) begin
    tmp_62_reg_631[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    ap_return_preg[63] <= 1'b0;
end

endmodule //scaled_fixed2ieee
