// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _write_FFT_data_1200_HH_
#define _write_FFT_data_1200_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct write_FFT_data_1200 : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<24> > fft_config_data_V_dout;
    sc_in< sc_logic > fft_config_data_V_empty_n;
    sc_out< sc_logic > fft_config_data_V_read;
    sc_out< sc_lv<24> > fft_config_data_V_din;
    sc_in< sc_logic > fft_config_data_V_full_n;
    sc_out< sc_logic > fft_config_data_V_write;
    sc_out< sc_lv<64> > to_FFT_2_din;
    sc_in< sc_logic > to_FFT_2_full_n;
    sc_out< sc_logic > to_FFT_2_write;
    sc_in< sc_lv<64> > to_FFT_dout;
    sc_in< sc_logic > to_FFT_empty_n;
    sc_out< sc_logic > to_FFT_read;


    // Module declarations
    write_FFT_data_1200(sc_module_name name);
    SC_HAS_PROCESS(write_FFT_data_1200);

    ~write_FFT_data_1200();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > fft_config_data_V_i_blk_n;
    sc_signal< sc_logic > fft_config_data_V_o_blk_n;
    sc_signal< sc_logic > to_FFT_2_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > exitcond_fu_97_p2;
    sc_signal< sc_logic > to_FFT_blk_n;
    sc_signal< sc_lv<11> > i_1_fu_103_p2;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_lv<11> > i_reg_73;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<21> ap_const_lv21_AAAAD;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<11> ap_const_lv11_400;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1();
    void thread_ap_block_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond_fu_97_p2();
    void thread_fft_config_data_V_din();
    void thread_fft_config_data_V_i_blk_n();
    void thread_fft_config_data_V_o_blk_n();
    void thread_fft_config_data_V_read();
    void thread_fft_config_data_V_write();
    void thread_i_1_fu_103_p2();
    void thread_internal_ap_ready();
    void thread_real_start();
    void thread_start_out();
    void thread_start_write();
    void thread_to_FFT_2_blk_n();
    void thread_to_FFT_2_din();
    void thread_to_FFT_2_write();
    void thread_to_FFT_blk_n();
    void thread_to_FFT_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
