// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dummy_proc_fe.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dummy_proc_fe::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dummy_proc_fe::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> dummy_proc_fe::ap_ST_fsm_state1 = "1";
const sc_lv<2> dummy_proc_fe::ap_ST_fsm_state2 = "10";
const sc_lv<32> dummy_proc_fe::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dummy_proc_fe::ap_const_lv32_1 = "1";
const sc_lv<1> dummy_proc_fe::ap_const_lv1_0 = "0";
const sc_lv<11> dummy_proc_fe::ap_const_lv11_0 = "00000000000";
const sc_lv<10> dummy_proc_fe::ap_const_lv10_2AB = "1010101011";
const sc_lv<16> dummy_proc_fe::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> dummy_proc_fe::ap_const_lv32_A = "1010";
const sc_lv<11> dummy_proc_fe::ap_const_lv11_400 = "10000000000";
const sc_lv<11> dummy_proc_fe::ap_const_lv11_1 = "1";
const sc_lv<1> dummy_proc_fe::ap_const_lv1_1 = "1";
const bool dummy_proc_fe::ap_const_boolean_1 = true;

dummy_proc_fe::dummy_proc_fe(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( direction_ap_vld );
    sensitive << ( config_data_V_full_n );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_config_data_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( config_data_V_full_n );

    SC_METHOD(thread_config_data_V_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( direction_ap_vld );
    sensitive << ( config_data_V_full_n );
    sensitive << ( tmp_6_fu_114_p3 );

    SC_METHOD(thread_config_data_V_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( direction_ap_vld );
    sensitive << ( config_data_V_full_n );

    SC_METHOD(thread_direction_ap_ack);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( direction_ap_vld );
    sensitive << ( config_data_V_full_n );

    SC_METHOD(thread_direction_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( direction_ap_vld );

    SC_METHOD(thread_exitcond_fu_135_p2);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );
    sensitive << ( i_reg_103 );

    SC_METHOD(thread_i_1_fu_141_p2);
    sensitive << ( i_reg_103 );

    SC_METHOD(thread_in_r_blk_n);
    sensitive << ( in_r_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_in_r_read);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_out_r_blk_n);
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_out_r_din);
    sensitive << ( in_r_dout );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_out_r_write);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_6_fu_114_p3);
    sensitive << ( direction );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( direction_ap_vld );
    sensitive << ( config_data_V_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_135_p2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dummy_proc_fe_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, direction, "(port)direction");
    sc_trace(mVcdFile, direction_ap_vld, "(port)direction_ap_vld");
    sc_trace(mVcdFile, direction_ap_ack, "(port)direction_ap_ack");
    sc_trace(mVcdFile, config_data_V_din, "(port)config_data_V_din");
    sc_trace(mVcdFile, config_data_V_full_n, "(port)config_data_V_full_n");
    sc_trace(mVcdFile, config_data_V_write, "(port)config_data_V_write");
    sc_trace(mVcdFile, in_r_dout, "(port)in_r_dout");
    sc_trace(mVcdFile, in_r_empty_n, "(port)in_r_empty_n");
    sc_trace(mVcdFile, in_r_read, "(port)in_r_read");
    sc_trace(mVcdFile, out_r_din, "(port)out_r_din");
    sc_trace(mVcdFile, out_r_full_n, "(port)out_r_full_n");
    sc_trace(mVcdFile, out_r_write, "(port)out_r_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, direction_blk_n, "direction_blk_n");
    sc_trace(mVcdFile, config_data_V_blk_n, "config_data_V_blk_n");
    sc_trace(mVcdFile, in_r_blk_n, "in_r_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_fu_135_p2, "exitcond_fu_135_p2");
    sc_trace(mVcdFile, out_r_blk_n, "out_r_blk_n");
    sc_trace(mVcdFile, i_1_fu_141_p2, "i_1_fu_141_p2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, i_reg_103, "i_reg_103");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_6_fu_114_p3, "tmp_6_fu_114_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dummy_proc_fe::~dummy_proc_fe() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dummy_proc_fe::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))) && 
                    esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))))) {
        i_reg_103 = i_1_fu_141_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, direction_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, config_data_V_full_n.read())))) {
        i_reg_103 = ap_const_lv11_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
}

void dummy_proc_fe::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dummy_proc_fe::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dummy_proc_fe::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, direction_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, config_data_V_full_n.read()));
}

void dummy_proc_fe::thread_ap_block_state2() {
    ap_block_state2 = ((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())));
}

void dummy_proc_fe::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))) && 
         esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dummy_proc_fe::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dummy_proc_fe::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void dummy_proc_fe::thread_config_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        config_data_V_blk_n = config_data_V_full_n.read();
    } else {
        config_data_V_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_fe::thread_config_data_V_din() {
    config_data_V_din = esl_partset<16,16,11,32,32>(ap_const_lv16_0, tmp_6_fu_114_p3.read(), ap_const_lv32_0, ap_const_lv32_A);
}

void dummy_proc_fe::thread_config_data_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, direction_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, config_data_V_full_n.read())))) {
        config_data_V_write = ap_const_logic_1;
    } else {
        config_data_V_write = ap_const_logic_0;
    }
}

void dummy_proc_fe::thread_direction_ap_ack() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, direction_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, config_data_V_full_n.read())))) {
        direction_ap_ack = ap_const_logic_1;
    } else {
        direction_ap_ack = ap_const_logic_0;
    }
}

void dummy_proc_fe::thread_direction_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        direction_blk_n = direction_ap_vld.read();
    } else {
        direction_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_fe::thread_exitcond_fu_135_p2() {
    exitcond_fu_135_p2 = (!i_reg_103.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_103.read() == ap_const_lv11_400);
}

void dummy_proc_fe::thread_i_1_fu_141_p2() {
    i_1_fu_141_p2 = (!i_reg_103.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_reg_103.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void dummy_proc_fe::thread_in_r_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0))) {
        in_r_blk_n = in_r_empty_n.read();
    } else {
        in_r_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_fe::thread_in_r_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))))) {
        in_r_read = ap_const_logic_1;
    } else {
        in_r_read = ap_const_logic_0;
    }
}

void dummy_proc_fe::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))) && 
         esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void dummy_proc_fe::thread_out_r_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0))) {
        out_r_blk_n = out_r_full_n.read();
    } else {
        out_r_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_fe::thread_out_r_din() {
    out_r_din = in_r_dout.read();
}

void dummy_proc_fe::thread_out_r_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))))) {
        out_r_write = ap_const_logic_1;
    } else {
        out_r_write = ap_const_logic_0;
    }
}

void dummy_proc_fe::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void dummy_proc_fe::thread_start_out() {
    start_out = real_start.read();
}

void dummy_proc_fe::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void dummy_proc_fe::thread_tmp_6_fu_114_p3() {
    tmp_6_fu_114_p3 = esl_concat<10,1>(ap_const_lv10_2AB, direction.read());
}

void dummy_proc_fe::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, direction_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, config_data_V_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))) && esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_135_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

