// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dummy_proc_be.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dummy_proc_be::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dummy_proc_be::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> dummy_proc_be::ap_ST_fsm_state1 = "1";
const sc_lv<2> dummy_proc_be::ap_ST_fsm_state2 = "10";
const sc_lv<32> dummy_proc_be::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dummy_proc_be::ap_const_lv32_1 = "1";
const sc_lv<1> dummy_proc_be::ap_const_lv1_1 = "1";
const sc_lv<1> dummy_proc_be::ap_const_lv1_0 = "0";
const sc_lv<11> dummy_proc_be::ap_const_lv11_0 = "00000000000";
const sc_lv<11> dummy_proc_be::ap_const_lv11_400 = "10000000000";
const sc_lv<11> dummy_proc_be::ap_const_lv11_1 = "1";
const bool dummy_proc_be::ap_const_boolean_1 = true;

dummy_proc_be::dummy_proc_be(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_exitcond_fu_106_p2);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );
    sensitive << ( i_reg_95 );

    SC_METHOD(thread_i_2_fu_112_p2);
    sensitive << ( i_reg_95 );

    SC_METHOD(thread_in_r_blk_n);
    sensitive << ( in_r_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_in_r_read);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_out_r_blk_n);
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_out_r_din);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_dout );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_out_r_write);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_ovflo_blk_n);
    sensitive << ( ovflo_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_ovflo_din);
    sensitive << ( status_in_data_V_dout );
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_ovflo_write);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_status_in_data_V_blk_n);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_status_in_data_V_read);
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( status_in_data_V_empty_n );
    sensitive << ( ovflo_full_n );
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_106_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dummy_proc_be_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, status_in_data_V_dout, "(port)status_in_data_V_dout");
    sc_trace(mVcdFile, status_in_data_V_empty_n, "(port)status_in_data_V_empty_n");
    sc_trace(mVcdFile, status_in_data_V_read, "(port)status_in_data_V_read");
    sc_trace(mVcdFile, ovflo_din, "(port)ovflo_din");
    sc_trace(mVcdFile, ovflo_full_n, "(port)ovflo_full_n");
    sc_trace(mVcdFile, ovflo_write, "(port)ovflo_write");
    sc_trace(mVcdFile, in_r_dout, "(port)in_r_dout");
    sc_trace(mVcdFile, in_r_empty_n, "(port)in_r_empty_n");
    sc_trace(mVcdFile, in_r_read, "(port)in_r_read");
    sc_trace(mVcdFile, out_r_din, "(port)out_r_din");
    sc_trace(mVcdFile, out_r_full_n, "(port)out_r_full_n");
    sc_trace(mVcdFile, out_r_write, "(port)out_r_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, status_in_data_V_blk_n, "status_in_data_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_fu_106_p2, "exitcond_fu_106_p2");
    sc_trace(mVcdFile, ovflo_blk_n, "ovflo_blk_n");
    sc_trace(mVcdFile, in_r_blk_n, "in_r_blk_n");
    sc_trace(mVcdFile, out_r_blk_n, "out_r_blk_n");
    sc_trace(mVcdFile, i_2_fu_112_p2, "i_2_fu_112_p2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, i_reg_95, "i_reg_95");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dummy_proc_be::~dummy_proc_be() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dummy_proc_be::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
                    !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
        i_reg_95 = i_2_fu_112_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_reg_95 = ap_const_lv11_0;
    }
}

void dummy_proc_be::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dummy_proc_be::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dummy_proc_be::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dummy_proc_be::thread_ap_block_state2() {
    ap_block_state2 = ((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read())));
}

void dummy_proc_be::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
         !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dummy_proc_be::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
         !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_exitcond_fu_106_p2() {
    exitcond_fu_106_p2 = (!i_reg_95.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_95.read() == ap_const_lv11_400);
}

void dummy_proc_be::thread_i_2_fu_112_p2() {
    i_2_fu_112_p2 = (!i_reg_95.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_reg_95.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void dummy_proc_be::thread_in_r_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0))) {
        in_r_blk_n = in_r_empty_n.read();
    } else {
        in_r_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_be::thread_in_r_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
        in_r_read = ap_const_logic_1;
    } else {
        in_r_read = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_out_r_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0))) {
        out_r_blk_n = out_r_full_n.read();
    } else {
        out_r_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_be::thread_out_r_din() {
    out_r_din = in_r_dout.read();
}

void dummy_proc_be::thread_out_r_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
        out_r_write = ap_const_logic_1;
    } else {
        out_r_write = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_ovflo_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1))) {
        ovflo_blk_n = ovflo_full_n.read();
    } else {
        ovflo_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_be::thread_ovflo_din() {
    ovflo_din =  (sc_logic) (status_in_data_V_dout.read()[0]);
}

void dummy_proc_be::thread_ovflo_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
         !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
        ovflo_write = ap_const_logic_1;
    } else {
        ovflo_write = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_status_in_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1))) {
        status_in_data_V_blk_n = status_in_data_V_empty_n.read();
    } else {
        status_in_data_V_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_be::thread_status_in_data_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
         !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
        status_in_data_V_read = ap_const_logic_1;
    } else {
        status_in_data_V_read = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, status_in_data_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_106_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ovflo_full_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

