// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dummy_proc_fe (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        direction,
        direction_ap_vld,
        direction_ap_ack,
        config_data_V_din,
        config_data_V_full_n,
        config_data_V_write,
        in_r_dout,
        in_r_empty_n,
        in_r_read,
        out_r_din,
        out_r_full_n,
        out_r_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    ap_const_lv16_0 = 16'd0;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [0:0] direction;
input   direction_ap_vld;
output   direction_ap_ack;
output  [15:0] config_data_V_din;
input   config_data_V_full_n;
output   config_data_V_write;
input  [31:0] in_r_dout;
input   in_r_empty_n;
output   in_r_read;
output  [31:0] out_r_din;
input   out_r_full_n;
output   out_r_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg direction_ap_ack;
reg config_data_V_write;
reg in_r_read;
reg out_r_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    direction_blk_n;
reg    config_data_V_blk_n;
reg    in_r_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond_fu_135_p2;
reg    out_r_blk_n;
wire   [10:0] i_1_fu_141_p2;
reg    ap_block_state2;
reg   [10:0] i_reg_103;
reg    ap_block_state1;
wire   [10:0] tmp_6_fu_114_p3;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_103 <= i_1_fu_141_p2;
    end else if ((~((real_start == 1'b0) | (config_data_V_full_n == 1'b0) | (direction_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_103 <= 11'd0;
    end
end

always @ (*) begin
    if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_data_V_blk_n = config_data_V_full_n;
    end else begin
        config_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_data_V_full_n == 1'b0) | (direction_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_data_V_write = 1'b1;
    end else begin
        config_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_data_V_full_n == 1'b0) | (direction_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        direction_ap_ack = 1'b1;
    end else begin
        direction_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        direction_blk_n = direction_ap_vld;
    end else begin
        direction_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        in_r_blk_n = in_r_empty_n;
    end else begin
        in_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        in_r_read = 1'b1;
    end else begin
        in_r_read = 1'b0;
    end
end

always @ (*) begin
    if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_r_blk_n = out_r_full_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_r_write = 1'b1;
    end else begin
        out_r_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (config_data_V_full_n == 1'b0) | (direction_ap_vld == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~(((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0))) & (exitcond_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (config_data_V_full_n == 1'b0) | (direction_ap_vld == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = (((exitcond_fu_135_p2 == 1'd0) & (out_r_full_n == 1'b0)) | ((exitcond_fu_135_p2 == 1'd0) & (in_r_empty_n == 1'b0)));
end

assign ap_ready = internal_ap_ready;

assign config_data_V_din = {{ap_const_lv16_0[15:11]}, {tmp_6_fu_114_p3}};

assign exitcond_fu_135_p2 = ((i_reg_103 == 11'd1024) ? 1'b1 : 1'b0);

assign i_1_fu_141_p2 = (i_reg_103 + 11'd1);

assign out_r_din = in_r_dout;

assign start_out = real_start;

assign tmp_6_fu_114_p3 = {{10'd683}, {direction}};

endmodule //dummy_proc_fe
