// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fft_top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xazu2eg-sbva484-1-i,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.888000,HLS_SYN_LAT=3195,HLS_SYN_TPT=3196,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=9932,HLS_SYN_LUT=8234,HLS_VERSION=2018_3}" *)

module fft_top (
        direction,
        in_r_dout,
        in_r_empty_n,
        in_r_read,
        out_r_din,
        out_r_full_n,
        out_r_write,
        ovflo_din,
        ovflo_full_n,
        ovflo_write,
        ap_clk,
        ap_rst,
        direction_ap_vld,
        direction_ap_ack,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input   direction;
input  [31:0] in_r_dout;
input   in_r_empty_n;
output   in_r_read;
output  [31:0] out_r_din;
input   out_r_full_n;
output   out_r_write;
output   ovflo_din;
input   ovflo_full_n;
output   ovflo_write;
input   ap_clk;
input   ap_rst;
input   direction_ap_vld;
output   direction_ap_ack;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    dummy_proc_fe_U0_ap_start;
wire    dummy_proc_fe_U0_start_full_n;
wire    dummy_proc_fe_U0_ap_done;
wire    dummy_proc_fe_U0_ap_continue;
wire    dummy_proc_fe_U0_ap_idle;
wire    dummy_proc_fe_U0_ap_ready;
wire    dummy_proc_fe_U0_start_out;
wire    dummy_proc_fe_U0_start_write;
wire   [0:0] dummy_proc_fe_U0_direction;
wire    dummy_proc_fe_U0_direction_ap_ack;
wire   [15:0] dummy_proc_fe_U0_config_data_V_din;
wire    dummy_proc_fe_U0_config_data_V_write;
wire    dummy_proc_fe_U0_in_r_read;
wire   [31:0] dummy_proc_fe_U0_out_r_din;
wire    dummy_proc_fe_U0_out_r_write;
wire    fft_config1_U0_ap_start;
wire    fft_config1_U0_ap_done;
wire    fft_config1_U0_ap_idle;
wire    fft_config1_U0_ap_ready;
wire    fft_config1_U0_ap_continue;
wire    fft_config1_U0_xn_read;
wire   [31:0] fft_config1_U0_xk_din;
wire    fft_config1_U0_xk_write;
wire   [7:0] fft_config1_U0_status_data_V_din;
wire    fft_config1_U0_status_data_V_write;
wire    fft_config1_U0_config_ch_data_V_read;
wire    dummy_proc_be_U0_ap_start;
wire    dummy_proc_be_U0_ap_done;
wire    dummy_proc_be_U0_ap_continue;
wire    dummy_proc_be_U0_ap_idle;
wire    dummy_proc_be_U0_ap_ready;
wire    dummy_proc_be_U0_status_in_data_V_read;
wire    dummy_proc_be_U0_ovflo_din;
wire    dummy_proc_be_U0_ovflo_write;
wire    dummy_proc_be_U0_in_r_read;
wire   [31:0] dummy_proc_be_U0_out_r_din;
wire    dummy_proc_be_U0_out_r_write;
wire    ap_sync_continue;
wire    fft_config_data_V_full_n;
wire   [15:0] fft_config_data_V_dout;
wire    fft_config_data_V_empty_n;
wire    xn_channel_full_n;
wire   [31:0] xn_channel_dout;
wire    xn_channel_empty_n;
wire    xk_channel_full_n;
wire   [31:0] xk_channel_dout;
wire    xk_channel_empty_n;
wire    fft_status_data_V_full_n;
wire   [7:0] fft_status_data_V_dout;
wire    fft_status_data_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_fft_config1_U0_din;
wire    start_for_fft_config1_U0_full_n;
wire   [0:0] start_for_fft_config1_U0_dout;
wire    start_for_fft_config1_U0_empty_n;
wire   [0:0] start_for_dummy_proc_be_U0_din;
wire    start_for_dummy_proc_be_U0_full_n;
wire   [0:0] start_for_dummy_proc_be_U0_dout;
wire    start_for_dummy_proc_be_U0_empty_n;
wire    fft_config1_U0_start_full_n;
wire    fft_config1_U0_start_write;
wire    dummy_proc_be_U0_start_full_n;
wire    dummy_proc_be_U0_start_write;

dummy_proc_fe dummy_proc_fe_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dummy_proc_fe_U0_ap_start),
    .start_full_n(dummy_proc_fe_U0_start_full_n),
    .ap_done(dummy_proc_fe_U0_ap_done),
    .ap_continue(dummy_proc_fe_U0_ap_continue),
    .ap_idle(dummy_proc_fe_U0_ap_idle),
    .ap_ready(dummy_proc_fe_U0_ap_ready),
    .start_out(dummy_proc_fe_U0_start_out),
    .start_write(dummy_proc_fe_U0_start_write),
    .direction(dummy_proc_fe_U0_direction),
    .direction_ap_vld(direction_ap_vld),
    .direction_ap_ack(dummy_proc_fe_U0_direction_ap_ack),
    .config_data_V_din(dummy_proc_fe_U0_config_data_V_din),
    .config_data_V_full_n(fft_config_data_V_full_n),
    .config_data_V_write(dummy_proc_fe_U0_config_data_V_write),
    .in_r_dout(in_r_dout),
    .in_r_empty_n(in_r_empty_n),
    .in_r_read(dummy_proc_fe_U0_in_r_read),
    .out_r_din(dummy_proc_fe_U0_out_r_din),
    .out_r_full_n(xn_channel_full_n),
    .out_r_write(dummy_proc_fe_U0_out_r_write)
);

fft_config1_s fft_config1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_config1_U0_ap_start),
    .ap_ce(1'b1),
    .ap_done(fft_config1_U0_ap_done),
    .ap_idle(fft_config1_U0_ap_idle),
    .ap_ready(fft_config1_U0_ap_ready),
    .ap_continue(fft_config1_U0_ap_continue),
    .xn_dout(xn_channel_dout),
    .xn_empty_n(xn_channel_empty_n),
    .xn_read(fft_config1_U0_xn_read),
    .xk_din(fft_config1_U0_xk_din),
    .xk_full_n(xk_channel_full_n),
    .xk_write(fft_config1_U0_xk_write),
    .status_data_V_din(fft_config1_U0_status_data_V_din),
    .status_data_V_full_n(fft_status_data_V_full_n),
    .status_data_V_write(fft_config1_U0_status_data_V_write),
    .config_ch_data_V_dout(fft_config_data_V_dout),
    .config_ch_data_V_empty_n(fft_config_data_V_empty_n),
    .config_ch_data_V_read(fft_config1_U0_config_ch_data_V_read)
);

dummy_proc_be dummy_proc_be_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dummy_proc_be_U0_ap_start),
    .ap_done(dummy_proc_be_U0_ap_done),
    .ap_continue(dummy_proc_be_U0_ap_continue),
    .ap_idle(dummy_proc_be_U0_ap_idle),
    .ap_ready(dummy_proc_be_U0_ap_ready),
    .status_in_data_V_dout(fft_status_data_V_dout),
    .status_in_data_V_empty_n(fft_status_data_V_empty_n),
    .status_in_data_V_read(dummy_proc_be_U0_status_in_data_V_read),
    .ovflo_din(dummy_proc_be_U0_ovflo_din),
    .ovflo_full_n(ovflo_full_n),
    .ovflo_write(dummy_proc_be_U0_ovflo_write),
    .in_r_dout(xk_channel_dout),
    .in_r_empty_n(xk_channel_empty_n),
    .in_r_read(dummy_proc_be_U0_in_r_read),
    .out_r_din(dummy_proc_be_U0_out_r_din),
    .out_r_full_n(out_r_full_n),
    .out_r_write(dummy_proc_be_U0_out_r_write)
);

fifo_w16_d1_A fft_config_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe_U0_config_data_V_din),
    .if_full_n(fft_config_data_V_full_n),
    .if_write(dummy_proc_fe_U0_config_data_V_write),
    .if_dout(fft_config_data_V_dout),
    .if_empty_n(fft_config_data_V_empty_n),
    .if_read(fft_config1_U0_config_ch_data_V_read)
);

fifo_w32_d1_A xn_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe_U0_out_r_din),
    .if_full_n(xn_channel_full_n),
    .if_write(dummy_proc_fe_U0_out_r_write),
    .if_dout(xn_channel_dout),
    .if_empty_n(xn_channel_empty_n),
    .if_read(fft_config1_U0_xn_read)
);

fifo_w32_d1_A xk_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_U0_xk_din),
    .if_full_n(xk_channel_full_n),
    .if_write(fft_config1_U0_xk_write),
    .if_dout(xk_channel_dout),
    .if_empty_n(xk_channel_empty_n),
    .if_read(dummy_proc_be_U0_in_r_read)
);

fifo_w8_d1_A fft_status_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_U0_status_data_V_din),
    .if_full_n(fft_status_data_V_full_n),
    .if_write(fft_config1_U0_status_data_V_write),
    .if_dout(fft_status_data_V_dout),
    .if_empty_n(fft_status_data_V_empty_n),
    .if_read(dummy_proc_be_U0_status_in_data_V_read)
);

start_for_fft_config1_U0 start_for_fft_config1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_config1_U0_din),
    .if_full_n(start_for_fft_config1_U0_full_n),
    .if_write(dummy_proc_fe_U0_start_write),
    .if_dout(start_for_fft_config1_U0_dout),
    .if_empty_n(start_for_fft_config1_U0_empty_n),
    .if_read(fft_config1_U0_ap_ready)
);

start_for_dummy_proc_be_U0 start_for_dummy_proc_be_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dummy_proc_be_U0_din),
    .if_full_n(start_for_dummy_proc_be_U0_full_n),
    .if_write(dummy_proc_fe_U0_start_write),
    .if_dout(start_for_dummy_proc_be_U0_dout),
    .if_empty_n(start_for_dummy_proc_be_U0_empty_n),
    .if_read(dummy_proc_be_U0_ap_ready)
);

assign ap_done = dummy_proc_be_U0_ap_done;

assign ap_idle = (fft_config1_U0_ap_idle & dummy_proc_fe_U0_ap_idle & dummy_proc_be_U0_ap_idle);

assign ap_ready = dummy_proc_fe_U0_ap_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = dummy_proc_be_U0_ap_done;

assign ap_sync_ready = dummy_proc_fe_U0_ap_ready;

assign direction_ap_ack = dummy_proc_fe_U0_direction_ap_ack;

assign dummy_proc_be_U0_ap_continue = 1'b1;

assign dummy_proc_be_U0_ap_start = start_for_dummy_proc_be_U0_empty_n;

assign dummy_proc_be_U0_start_full_n = 1'b1;

assign dummy_proc_be_U0_start_write = 1'b0;

assign dummy_proc_fe_U0_ap_continue = 1'b1;

assign dummy_proc_fe_U0_ap_start = ap_start;

assign dummy_proc_fe_U0_direction = direction;

assign dummy_proc_fe_U0_start_full_n = (start_for_fft_config1_U0_full_n & start_for_dummy_proc_be_U0_full_n);

assign fft_config1_U0_ap_continue = 1'b1;

assign fft_config1_U0_ap_start = start_for_fft_config1_U0_empty_n;

assign fft_config1_U0_start_full_n = 1'b1;

assign fft_config1_U0_start_write = 1'b0;

assign in_r_read = dummy_proc_fe_U0_in_r_read;

assign out_r_din = dummy_proc_be_U0_out_r_din;

assign out_r_write = dummy_proc_be_U0_out_r_write;

assign ovflo_din = dummy_proc_be_U0_ovflo_din;

assign ovflo_write = dummy_proc_be_U0_ovflo_write;

assign start_for_dummy_proc_be_U0_din = 1'b1;

assign start_for_fft_config1_U0_din = 1'b1;

endmodule //fft_top
