-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity write_FFT_data_1200 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    fft_config_data_V_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    fft_config_data_V_empty_n : IN STD_LOGIC;
    fft_config_data_V_read : OUT STD_LOGIC;
    fft_config_data_V_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    fft_config_data_V_full_n : IN STD_LOGIC;
    fft_config_data_V_write : OUT STD_LOGIC;
    to_FFT_2_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    to_FFT_2_full_n : IN STD_LOGIC;
    to_FFT_2_write : OUT STD_LOGIC;
    to_FFT_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    to_FFT_empty_n : IN STD_LOGIC;
    to_FFT_read : OUT STD_LOGIC );
end;


architecture behav of write_FFT_data_1200 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv21_AAAAD : STD_LOGIC_VECTOR (20 downto 0) := "010101010101010101101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal fft_config_data_V_i_blk_n : STD_LOGIC;
    signal fft_config_data_V_o_blk_n : STD_LOGIC;
    signal to_FFT_2_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal exitcond_fu_97_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal to_FFT_blk_n : STD_LOGIC;
    signal i_1_fu_103_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal i_reg_73 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_reg_73_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_reg_73 <= i_1_fu_103_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (fft_config_data_V_full_n = ap_const_logic_0) or (fft_config_data_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_73 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, fft_config_data_V_empty_n, fft_config_data_V_full_n, to_FFT_2_full_n, to_FFT_empty_n, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (fft_config_data_V_full_n = ap_const_logic_0) or (fft_config_data_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, fft_config_data_V_empty_n, fft_config_data_V_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (fft_config_data_V_full_n = ap_const_logic_0) or (fft_config_data_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(to_FFT_2_full_n, to_FFT_empty_n, exitcond_fu_97_p2)
    begin
                ap_block_state2 <= (((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, to_FFT_2_full_n, to_FFT_empty_n, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    exitcond_fu_97_p2 <= "1" when (i_reg_73 = ap_const_lv11_400) else "0";
    fft_config_data_V_din <= (fft_config_data_V_dout(23 downto 21) & ap_const_lv21_AAAAD);

    fft_config_data_V_i_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, fft_config_data_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fft_config_data_V_i_blk_n <= fft_config_data_V_empty_n;
        else 
            fft_config_data_V_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fft_config_data_V_o_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, fft_config_data_V_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fft_config_data_V_o_blk_n <= fft_config_data_V_full_n;
        else 
            fft_config_data_V_o_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fft_config_data_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, fft_config_data_V_empty_n, fft_config_data_V_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (fft_config_data_V_full_n = ap_const_logic_0) or (fft_config_data_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fft_config_data_V_read <= ap_const_logic_1;
        else 
            fft_config_data_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fft_config_data_V_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, fft_config_data_V_empty_n, fft_config_data_V_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (fft_config_data_V_full_n = ap_const_logic_0) or (fft_config_data_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fft_config_data_V_write <= ap_const_logic_1;
        else 
            fft_config_data_V_write <= ap_const_logic_0;
        end if; 
    end process;

    i_1_fu_103_p2 <= std_logic_vector(unsigned(i_reg_73) + unsigned(ap_const_lv11_1));

    internal_ap_ready_assign_proc : process(to_FFT_2_full_n, to_FFT_empty_n, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    to_FFT_2_blk_n_assign_proc : process(to_FFT_2_full_n, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if (((exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            to_FFT_2_blk_n <= to_FFT_2_full_n;
        else 
            to_FFT_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    to_FFT_2_din <= to_FFT_dout;

    to_FFT_2_write_assign_proc : process(to_FFT_2_full_n, to_FFT_empty_n, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            to_FFT_2_write <= ap_const_logic_1;
        else 
            to_FFT_2_write <= ap_const_logic_0;
        end if; 
    end process;


    to_FFT_blk_n_assign_proc : process(to_FFT_empty_n, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if (((exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            to_FFT_blk_n <= to_FFT_empty_n;
        else 
            to_FFT_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    to_FFT_read_assign_proc : process(to_FFT_2_full_n, to_FFT_empty_n, ap_CS_fsm_state2, exitcond_fu_97_p2)
    begin
        if ((not((((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_2_full_n = ap_const_logic_0)) or ((exitcond_fu_97_p2 = ap_const_lv1_0) and (to_FFT_empty_n = ap_const_logic_0)))) and (exitcond_fu_97_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            to_FFT_read <= ap_const_logic_1;
        else 
            to_FFT_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
